services:
  - type: web
    name: ims-web
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /api/docs/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ims-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings

databases:
  - name: ims-db
    databaseName: ims_db
    user: ims_user
    plan: free 