# Generated by Django 4.2.7 on 2025-04-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('report_submission', 'Report Submission'), ('evaluation', 'Evaluation'), ('meeting', 'Meeting'), ('task_completion', 'Task Completion')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_internships', models.IntegerField(default=0)),
                ('active_internships', models.IntegerField(default=0)),
                ('completed_internships', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('student_count', 'Student Count'), ('active_internships', 'Active Internships'), ('completion_rate', 'Completion Rate'), ('mentor_count', 'Mentor Count')], max_length=50)),
                ('value', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'date'], name='dashboard_d_name_96c703_idx'), models.Index(fields=['-date'], name='dashboard_d_date_054a27_idx')],
                'unique_together': {('name', 'date')},
            },
        ),
    ]
