# Generated by Django 4.2.7 on 2025-04-16 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dashboardstat',
            index=models.Index(fields=['created_at'], name='dashboard_d_created_f49852_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardstat',
            index=models.Index(fields=['organization', 'created_at'], name='dashboard_d_organiz_5aaac2_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-created_at'], name='dashboard_a_user_id_7f2c17_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', '-created_at'], name='dashboard_a_activit_837855_idx'),
        ),
    ]
