# Generated by Django 4.2.7 on 2025-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_organization', 'Pending Organization Approval'), ('pending_university', 'Pending University Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('student_signature', models.BooleanField(default=False)),
                ('organization_signature', models.BooleanField(default=False)),
                ('university_signature', models.BooleanField(default=False)),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='agreements/%Y/%m/')),
                ('signed_agreement_file', models.FileField(blank=True, null=True, upload_to='signed_agreements/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_type', models.CharField(choices=[('teacher', 'Teacher'), ('mentor', 'Mentor')], default='teacher', max_length=20)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('comments', models.TextField()),
                ('feedback', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('work_hours', models.JSONField(default=dict)),
                ('total_hours', models.IntegerField(default=0)),
                ('technical_skill_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('communication_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('report_quality_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'internship',
                'verbose_name_plural': 'internships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='applications/cv/%Y/%m/')),
                ('cover_letter', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(help_text='Байгууллагын нэр', max_length=255)),
                ('position', models.CharField(help_text='Дадлагын нэр/Албан тушаал', max_length=255)),
                ('category', models.CharField(choices=[('Програм хангамж', 'Програм хангамж'), ('Дата шинжилгээ', 'Дата шинжилгээ'), ('Кибер аюулгүй байдал', 'Кибер аюулгүй байдал'), ('Маркетинг', 'Маркетинг'), ('Бизнес', 'Бизнес'), ('Санхүү', 'Санхүү'), ('Барилга инженер', 'Барилга инженер'), ('Бусад', 'Бусад')], help_text='Дадлагын ангилал', max_length=50)),
                ('type', models.CharField(choices=[('Бүтэн цагийн', 'Бүтэн цагийн'), ('Хагас цагийн', 'Хагас цагийн'), ('Зайнаас', 'Зайнаас'), ('Уян хатан', 'Уян хатан')], help_text='Дадлагын төрөл', max_length=50)),
                ('location', models.CharField(help_text='Дадлагын байршил', max_length=255)),
                ('duration', models.CharField(help_text='Дадлагын хугацаа', max_length=100)),
                ('salary', models.CharField(blank=True, help_text='Цалин/Урамшуулал', max_length=255, null=True)),
                ('salary_amount', models.IntegerField(blank=True, help_text='Цалингийн хэмжээ (тоогоор)', null=True)),
                ('description', models.TextField(help_text='Дадлагын тодорхойлолт')),
                ('requirements', models.JSONField(default=list, help_text='Шаардлагууд (жагсаалт)')),
                ('benefits', models.JSONField(default=list, help_text='Давуу талууд (жагсаалт)')),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='Хариуцах ажлууд', null=True)),
                ('logo', models.URLField(blank=True, help_text='Байгууллагын лого зургийн URL', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Онцлох дадлага эсэх')),
                ('active', models.BooleanField(default=True, help_text='Идэвхтэй эсэх')),
                ('applyDeadline', models.DateField(help_text='Хүсэлт хүлээн авах эцсийн хугацаа')),
                ('postedDate', models.DateField(auto_now_add=True, help_text='Нийтэлсэн огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Дадлагын Зар',
                'verbose_name_plural': 'Дадлагын Зарууд',
                'ordering': ['-featured', '-postedDate'],
            },
        ),
        migrations.CreateModel(
            name='InternshipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreliminaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='draft', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('final', 'Final Report')], max_length=20)),
                ('content', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
