# Generated by Django 4.2.7 on 2025-02-13 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='internships.internship'),
        ),
        migrations.AddField(
            model_name='report',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='internships.internship'),
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preliminaryreport',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_reports', to='internships.internship'),
        ),
        migrations.AddField(
            model_name='preliminaryreport',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_preliminary_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipplan',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipplan',
            name='internship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='internships.internship'),
        ),
        migrations.AddField(
            model_name='internship',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internship',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='companies.organization'),
        ),
        migrations.AddField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internships.report'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='internship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='internships.internship'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_agreements', to='companies.organization'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['student', 'status'], name='internships_student_39679a_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['mentor'], name='internships_mentor__d3b839_idx'),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['organization'], name='internships_organiz_d5174e_idx'),
        ),
    ]
