# Generated by Django 4.2.7 on 2025-04-16 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['is_active'], name='companies_w_is_acti_0d50b0_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['organization'], name='companies_w_organiz_0576f1_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status'], name='companies_w_status_272654_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['event_type'], name='companies_w_event_t_0bcfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['created_at'], name='companies_w_created_046c72_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['next_retry_at'], name='companies_w_next_re_e95ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organization_name_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['contact_person'], name='org_contact_person_idx'),
        ),
    ]
