# Generated by Django 4.2.7 on 2025-04-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'evaluation',
                'verbose_name_plural': 'evaluations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical Skills'), ('communication', 'Communication'), ('report', 'Report Quality'), ('attendance', 'Attendance'), ('teamwork', 'Teamwork')], max_length=20)),
                ('description', models.TextField()),
                ('max_score', models.DecimalField(decimal_places=1, default=10.0, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
            options={
                'verbose_name': 'evaluation criteria',
                'verbose_name_plural': 'evaluation criteria',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comments', models.TextField(blank=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcriteria')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'evaluation score',
                'verbose_name_plural': 'evaluation scores',
            },
        ),
        migrations.CreateModel(
            name='EvaluationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evaluations/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'evaluation attachment',
                'verbose_name_plural': 'evaluation attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
