# Generated by Django 4.2.7 on 2025-02-28 10:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_internshipapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evaluations/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['criteria__weight'],
            },
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='evaluationcriteria',
            options={'ordering': ['weight']},
        ),
        migrations.RemoveIndex(
            model_name='evaluation',
            name='evaluations_student_3db903_idx',
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='criteria_type',
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='is_active',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator_type',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('teacher', 'Teacher')], default='mentor', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='evaluator_type',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('teacher', 'Teacher')], default='mentor', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internships.internship'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('internship', 'evaluator_type')},
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['internship', 'evaluator_type'], name='evaluations_interns_4c56a4_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcriteria',
            index=models.Index(fields=['evaluator_type'], name='evaluations_evaluat_9fd5ed_idx'),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluationcriteria'),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationattachment',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='evaluations.evaluation'),
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluation_type',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='student',
        ),
        migrations.AddIndex(
            model_name='evaluationscore',
            index=models.Index(fields=['evaluation', 'criteria'], name='evaluations_evaluat_d6202a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationscore',
            unique_together={('evaluation', 'criteria')},
        ),
        migrations.AddIndex(
            model_name='evaluationattachment',
            index=models.Index(fields=['evaluation', 'created_at'], name='evaluations_evaluat_440ecd_idx'),
        ),
    ]
