# Generated by Django 4.2.7 on 2025-02-28 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='sections',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
